theme: jekyll-theme-minimal
logo: /assets/avatar.png
title: Gleb Remniov (Hleb Ramniou)
description: This is my personal web-page. You can find there some information about me, my works and my projects.